language: objective-c
rvm: 2.2.5
cache: cocoapods
osx_image: xcode8.1

before_install:
- gem install xcov --no-ri --no-rdoc --no-document
- gem update fastlane --no-ri --no-rdoc --no-document

install: true

before_script:
- travis/create-keychain.sh

script: travis/script.sh
after_success: travis/after_success_script.sh